name: receipt-processor-challenge-dev
services:
  api-dev:
    build:
      context: .
      target: build

    volumes:
      - ./:/app
      - /app/node_modules

    ports:
      - 3000:3000

    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/health || exit 1']
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 3s

    command: pnpm run dev
